const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dualCodexDay', Object.freeze({
  getSnapshot: profileId => ipcRenderer.invoke('app:get-snapshot', profileId),
  createProfile: name => ipcRenderer.invoke('profiles:create', name),
  renameProfile: (profileId, name) => ipcRenderer.invoke('profiles:rename', { profileId, name }),
  deleteProfile: profileId => ipcRenderer.invoke('profiles:delete', profileId),
  previewProvider: (profileId, provider) => ipcRenderer.invoke('profiles:provider-preview', { profileId, provider }),
  saveProvider: (profileId, provider, apiKey) => ipcRenderer.invoke('profiles:save-provider', { profileId, provider, apiKey }),
  setProfileUsageSource: (profileId, source) => ipcRenderer.invoke('profiles:set-usage-source', { profileId, source }),
  setProfileRuntimeSource: (profileId, source) => ipcRenderer.invoke('profiles:set-runtime-source', { profileId, source }),
  importProfileConfig: profileId => ipcRenderer.invoke('profiles:import-config', profileId),
  exportProfileTransfer: (profileId, preferences) => ipcRenderer.invoke('profiles:export-transfer', { profileId, preferences }),
  chooseProfileTransfer: () => ipcRenderer.invoke('profiles:choose-transfer'),
  applyProfileTransfer: token => ipcRenderer.invoke('profiles:apply-transfer', token),
  discardProfileTransfer: token => ipcRenderer.invoke('profiles:discard-transfer', token),
  diagnoseProfile: profileId => ipcRenderer.invoke('profiles:diagnose', profileId),
  exportProfileDiagnosis: token => ipcRenderer.invoke('profiles:export-diagnosis', token),
  discardProfileDiagnosis: token => ipcRenderer.invoke('profiles:discard-diagnosis', token),
  launchProfile: (profileId, target) => ipcRenderer.invoke('profiles:launch', { profileId, target }),
  stopProfileLaunch: launchId => ipcRenderer.invoke('profiles:stop', launchId),
  openProfileFolder: profileId => ipcRenderer.invoke('profiles:open-folder', profileId),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  getUsageData: sourceId => ipcRenderer.invoke('usage:get-data', sourceId),
  getUsageComparison: () => ipcRenderer.invoke('usage:get-comparison'),
  getCcSwitchAudit: databasePath => ipcRenderer.invoke('usage:cc-switch-audit', databasePath),
  chooseCcSwitchDatabase: () => ipcRenderer.invoke('usage:choose-cc-switch-db'),
  getSkills: () => ipcRenderer.invoke('skills:get'),
  shareSkill: (source, overwrite) => ipcRenderer.invoke('skills:share', { source, overwrite }),
  syncSkill: (source, targetRoot, overwrite) => ipcRenderer.invoke('skills:sync', { source, targetRoot, overwrite }),
  setSkillEnabled: (codexHome, skillPath, enabled) => ipcRenderer.invoke('skills:set-enabled', { codexHome, skillPath, enabled }),
  removeSkill: path => ipcRenderer.invoke('skills:remove', { path }),
  installPlugin: (pluginId, targetCodexHome) => ipcRenderer.invoke('plugins:install', { pluginId, targetCodexHome }),
  setPluginEnabled: (pluginId, codexHome, enabled) => ipcRenderer.invoke('plugins:set-enabled', { pluginId, codexHome, enabled }),
  removePlugin: (pluginId, codexHome) => ipcRenderer.invoke('plugins:remove', { pluginId, codexHome })
}));
