import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { discoverProjectSkillRoots, scanSkills, setSkillEnabled, syncSkill } from './lib/skill-store.mjs';

const root = mkdtempSync(path.join(os.tmpdir(), 'dcd-skills-'));
const home = path.join(root, 'home');
const codex = path.join(root, 'default');
const profile = path.join(root, 'profile');
const workspace = path.join(root, 'repo');
const makeSkill = (base, name, description = 'demo') => {
  const dir = path.join(base, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, 'SKILL.md'), `---\nname: ${name}\ndescription: ${description}\n---\n`, 'utf8');
  return dir;
};
makeSkill(path.join(home, '.agents', 'skills'), 'shared-one');
makeSkill(path.join(codex, 'skills'), 'shared-one', 'default copy');
makeSkill(path.join(profile, 'skills'), 'profile-only');
makeSkill(path.join(codex, 'skills', '.system'), 'bundled');
const discoveredWorkspace = path.join(root, 'documents', 'project-a');
makeSkill(path.join(discoveredWorkspace, '.agents', 'skills'), 'discovered-one');
mkdirSync(path.join(root, 'documents', 'project-b', 'node_modules', 'ignored', '.agents', 'skills'), { recursive: true });
const discovered = discoverProjectSkillRoots([path.join(root, 'documents')]);
assert.equal(discovered.length, 1);
assert.equal(discovered[0].workspace, discoveredWorkspace);
const result = scanSkills({ profiles: [{ id: 'p1', name: 'HL', codexHome: profile, runtimeSource: 'profile' }], workspace, projectSkillRoots: discovered, defaultCodexHome: codex, sharedSkillsRoot: path.join(home, '.agents', 'skills') });
assert.equal(result.skills.find(item => item.name === 'shared-one')?.conflict, true);
assert.equal(result.skills.find(item => item.name === 'bundled')?.availability.system, true);
assert.equal(result.skills.find(item => item.name === 'profile-only')?.availability.profiles[0], 'HL');
assert.equal(result.skills.find(item => item.name === 'discovered-one')?.availability.workspace, true);
assert.equal(result.roots.find(item => item.label.includes('自动发现'))?.managed, false);
syncSkill(path.join(home, '.agents', 'skills', 'shared-one'), path.join(profile, 'skills'));
writeFileSync(path.join(profile, 'skills', 'shared-one', 'stale.txt'), 'stale', 'utf8');
syncSkill(path.join(home, '.agents', 'skills', 'shared-one'), path.join(profile, 'skills'), { overwrite: true });
assert.equal(readFileSync(path.join(profile, 'skills', 'shared-one', 'SKILL.md'), 'utf8').includes('shared-one'), true);
assert.equal(result.roots.some(root => root.scope === 'shared'), true);
const configHome = path.join(root, 'config');
mkdirSync(configHome, { recursive: true });
writeFileSync(path.join(configHome, 'config.toml'), '[general]\nfoo = "bar"\n', 'utf8');
setSkillEnabled(configHome, path.join(home, '.agents', 'skills', 'shared-one', 'SKILL.md'), false);
const config = readFileSync(path.join(configHome, 'config.toml'), 'utf8');
assert.match(config, /foo = "bar"/);
assert.match(config, /enabled = false/);
console.log('Skills checks passed.');
